# Generated by Django 5.2.2 on 2025-06-05 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": [("manage_category", "Can add/change/delete category")]
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("manage_product", "Can add/change/delete product")]
            },
        ),
    ]
