# Generated by Django 5.2.2 on 2025-06-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_order_address_order_city_order_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="product_images/"),
        ),
    ]
